export const ACCESS_TOKEN = 'AccessToken'
export const USER_ID = 'userId'
export const PLATFORM = 'platform'
export const OPENID = 'openid'
export const URL = 'url'
export const USERINFO = 'user_info'
