<?php
/**
 * Created by PhpStorm.
 * User: wenhan
 * Date: 2022/1/22
 * Time: 下午10:22
 */
Route::group('api', function(){
    //溯源模块
    Route::rule('trace/getPageData','api/trace.page/getPageData');
    Route::rule('trace/getCompanyInfo','api/trace.page/getCompanyInfo');
    //物流模块
    Route::rule('wl/getPageData','api/wl.page/getPageData');
    Route::rule('wl/getCompanyInfo','api/wl.page/getCompanyInfo');
    Route::rule('wl/getWarehouseList','api/wl.page/getWarehouseList');
    Route::rule('wl/queryLogisticsInfo','api/wl.page/queryLogisticsInfo');
    //二维码营销
    Route::rule('qrcode/getAuthInfo','api/qrcode.auth/getAuthInfo');
    Route::rule('qrcode/getUserInfo','api/qrcode.auth/getUserInfo');
    Route::rule('qrcode/getUserOpenid','api/qrcode.auth/getUserOpenid');
    Route::rule('qrcode/getJsConfig','api/qrcode.auth/getJsConfig');
    Route::rule('qrcode/getTpl','api/qrcode.tpl/getTpl');
    Route::rule('qrcode/getPrize','api/qrcode.prize/getPrize');
    Route::rule('qrcode/uploadFile','api/qrcode.prize/uploadFile');
    Route::rule('qrcode/saveRegisterInfo','api/qrcode.register/saveRegisterInfo');
    Route::rule('qrcode/getWorkType','api/qrcode.register/getWorkType');
    Route::rule('qrcode/getOperationCenter','api/qrcode.register/getOperationCenter');
    //积分模块
    Route::rule('points/getAuthInfo','api/points.auth/getAuthInfo');
    Route::rule('points/getAuthUserInfo','api/points.auth/getAuthUserInfo');
    Route::rule('points/getJsConfig','api/points.auth/getJsConfig');
    Route::rule('points/getPageData','api/points.page/getPageData');
    Route::rule('points/getHotRecommend','api/points.page/getHotRecommend');
    Route::rule('points/getPointsRule','api/points.rule/getPointsRule');
    Route::rule('points/getGiftsList','api/points.gift/getGiftsList');
    Route::rule('points/getGiftsInfo','api/points.gift/getGiftsInfo');
    Route::rule('points/getUserInfo','api/points.usercenter/getUserInfo');
    Route::rule('points/saveUserInfo','api/points.usercenter/saveUserInfo');
    Route::rule('points/getMemberAddressList','api/points.memberaddress/getMemberAddressList');
    Route::rule('points/saveMemberAddress','api/points.memberaddress/saveMemberAddress');
    Route::rule('points/deleMemberAddress','api/points.memberaddress/deleMemberAddress');
    Route::rule('points/setDefaultMemberAddress','api/points.memberaddress/setDefaultMemberAddress');
    Route::rule('points/queryMemberAddress','api/points.memberaddress/queryMemberAddress');
    Route::rule('points/getPointsBill','api/points.bill/getPointsBill');
    Route::rule('points/getPointsType','api/points.bill/getPointsType');

    Route::rule('points/addCart','api/points.cart/addCart');
    Route::rule('points/updateCart','api/points.cart/updateCart');
    Route::rule('points/getCartList','api/points.cart/getCartList');
    Route::rule('points/clearCart','api/points.cart/clearCart');
    Route::rule('points/getOrderInfo','api/points.gift/getOrderInfo');
    Route::rule('points/settlement','api/points.pay/settlement');
    Route::rule('points/createOrder','api/points.pay/createOrder');
    Route::rule('points/getMyOrder','api/points.order/getMyOrder');
    Route::rule('points/cancelMyOrder','api/points.order/cancelMyOrder');
    Route::rule('points/getOrderDesById','api/points.order/getOrderDesById');
    Route::rule('points/checkOrder','api/points.pay/checkOrder');
    Route::rule('points/payOrder','api/points.pay/payOrder');
    Route::rule('points/getLogisticsCompany','api/points.order/getLogisticsCompany');
    Route::rule('points/receiving','api/points.pay/receiving');

    //商城模块
    Route::rule('mall/getAuthInfo','api/mall.auth/getAuthInfo');
    Route::rule('mall/getAuthUserInfo','api/mall.auth/getAuthUserInfo');
    Route::rule('mall/getJsConfig','api/mall.auth/getJsConfig');
    Route::rule('mall/getPageData','api/mall.page/getPageData');
    Route::rule('mall/getHotRecommend','api/mall.page/getHotRecommend');
    Route::rule('mall/getGoodsList','api/mall.goods/getGoodsList');
    Route::rule('mall/getGoodsType','api/mall.goods/getGoodsType');
    Route::rule('mall/getGoodsInfo','api/mall.goods/getGoodsInfo');
    Route::rule('mall/addCart','api/mall.cart/addCart');
    Route::rule('mall/updateCart','api/mall.cart/updateCart');
    Route::rule('mall/getCartList','api/mall.cart/getCartList');
    Route::rule('mall/clearCart','api/mall.cart/clearCart');
    Route::rule('mall/getMemberAddressList','api/mall.memberaddress/getMemberAddressList');
    Route::rule('mall/saveMemberAddress','api/mall.memberaddress/saveMemberAddress');
    Route::rule('mall/deleMemberAddress','api/mall.memberaddress/deleMemberAddress');
    Route::rule('mall/setDefaultMemberAddress','api/mall.memberaddress/setDefaultMemberAddress');
    Route::rule('mall/queryMemberAddress','api/mall.memberaddress/queryMemberAddress');
    Route::rule('mall/getUserInfo','api/mall.usercenter/getUserInfo');
    Route::rule('mall/saveUserInfo','api/mall.usercenter/saveUserInfo');
    Route::rule('mall/getOrderInfo','api/mall.goods/getOrderInfo');
    Route::rule('mall/createOrder','api/mall.pay/createOrder');
    Route::rule('mall/checkOrder','api/mall.pay/checkOrder');
    Route::rule('mall/cancelMyOrder','api/mall.order/cancelMyOrder');
    Route::rule('mall/getMyOrder','api/mall.order/getMyOrder');
    Route::rule('mall/getOrderDesById','api/mall.order/getOrderDesById');
    Route::rule('mall/getLogisticsCompany','api/mall.order/getLogisticsCompany');
    Route::rule('mall/receiving','api/mall.pay/receiving');
    Route::rule('mall/payOrder','api/mall.pay/payOrder');

    //导购模块
    Route::rule('guide/getAuthInfo','api/guide.auth/getAuthInfo');
    Route::rule('guide/getJsConfig','api/guide.auth/getJsConfig');
    Route::rule('guide/getUserInfo','api/guide.auth/getUserInfo');
    Route::rule('guide/getUserOpenid','api/guide.auth/getUserOpenid');
    Route::rule('guide/getStoreList','api/guide.register/getStoreList');
    Route::rule('guide/getGuideGroupList','api/guide.register/getGuideGroupList');
    Route::rule('guide/saveRegisterInfo','api/guide.register/saveRegisterInfo');
    Route::rule('guide/getTpl','api/guide.tpl/getTpl');
    Route::rule('guide/getPrize','api/guide.prize/getPrize');
    Route::rule('guide/getUserCenterPage','api/guide.usercenter/getUserCenterPage');//导购中心
    Route::rule('guide/getScanRecords','api/guide.usercenter/getScanRecords');//导购中心
    Route::rule('guide/getRrizeRecords','api/guide.usercenter/getRrizeRecords');//导购中心
    Route::rule('guide/getGuideUserInfo','api/guide.usercenter/getGuideUserInfo');//导购中心
    Route::rule('guide/getRankList','api/guide.usercenter/getRankList');//导购中心
    Route::rule('guide/getGuideGroupInfo','api/guide.usercenter/getGuideGroupInfo');//导购中心
    //导购营销
    Route::rule('multi/getAuthInfo','api/multi.auth/getAuthInfo');
    Route::rule('multi/getUserInfo','api/multi.auth/getUserInfo');
    Route::rule('multi/getJsConfig','api/multi.auth/getJsConfig');
    Route::rule('multi/getTpl','api/multi.tpl/getTpl');
    Route::rule('multi/getPrize','api/multi.prize/getPrize');
    Route::rule('multi/getRedTpl','api/multi.redtpl/getRedTpl');
    Route::rule('multi/getRedPrize','api/multi.redprize/getRedPrize');
    Route::rule('multi/queryCodeByOrder','api/multi.code/queryCodeByOrder');

    //智慧门店
    Route::rule('store/getVicinityStoreList','api/store.vicinity/getVicinityStoreList');
    Route::rule('store/getJsConfig','api/store.auth/getJsConfig');
    Route::rule('store/login','api/store.login/login');
    Route::rule('store/getNoticeList','api/store.notice/getNoticeList');
    Route::rule('store/getNoticeInfo','api/store.notice/getNoticeInfo');
    Route::rule('store/getStoreGoodsClass','api/store.goods/getStoreGoodsClass');
    Route::rule('store/getStoreGoods','api/store.goods/getStoreGoods');
    Route::rule('store/getStoreGoodsInfo','api/store.goods/getStoreGoodsInfo');
    Route::rule('store/saveStoreGoods','api/store.goods/saveStoreGoods');
    Route::rule('store/getSelfGoods','api/store.goods/getSelfGoods');
    Route::rule('store/cutSelfGoods','api/store.goods/cutSelfGoods');
    Route::rule('store/deleSelfGoods','api/store.goods/deleSelfGoods');
    Route::rule('store/getGuideList','api/store.guidemanage/getGuideList');
    Route::rule('store/checkGuide','api/store.guidemanage/checkGuide');
    Route::rule('store/getScanRecords','api/store.guidemanage/getScanRecords');
    Route::rule('store/getRrizeRecords','api/store.guidemanage/getRrizeRecords');
    Route::rule('store/checkOrderQrcode','api/store.check/checkOrderQrcode');
    Route::rule('store/getCheckLog','api/store.check/getCheckLog');
    Route::rule('store/getMyOrder','api/store.order/getMyOrder');
    Route::rule('store/getOrderDesById','api/store.order/getOrderDesById');
    Route::rule('store/getUserInfo','api/store.order/getUserInfo');

    //门店商城
    Route::rule('store_shop/getAuthInfo','api/store_shop.auth/getAuthInfo');
    Route::rule('store_shop/getAuthUserInfo','api/store_shop.auth/getAuthUserInfo');
    Route::rule('store_shop/getJsConfig','api/store_shop.auth/getJsConfig');
    Route::rule('store_shop/getStoreGoodsClass','api/store_shop.goods/getStoreGoodsClass');
    Route::rule('store_shop/getStoreGoods','api/store_shop.goods/getStoreGoods');
    Route::rule('store_shop/getStoreInfo','api/store_shop.store/getStoreInfo');
    Route::rule('store_shop/getGoodsInfo','api/store_shop.goods/getGoodsInfo');
    Route::rule('store_shop/getMemberAddressList','api/store_shop.address/getMemberAddressList');
    Route::rule('store_shop/queryMemberAddress','api/store_shop.address/queryMemberAddress');
    Route::rule('store_shop/saveMemberAddress','api/store_shop.address/saveMemberAddress');
    Route::rule('store_shop/addCart','api/store_shop.cart/addCart');
    Route::rule('store_shop/getCartList','api/store_shop.cart/getCartList');
    Route::rule('store_shop/updateCart','api/store_shop.cart/updateCart');
    Route::rule('store_shop/clearCart','api/store_shop.cart/clearCart');
    Route::rule('store_shop/getUserInfo','api/store_shop.usercenter/getUserInfo');
    Route::rule('store_shop/saveUserInfo','api/store_shop.usercenter/saveUserInfo');
    Route::rule('store_shop/getOrderInfo','api/store_shop.goods/getOrderInfo');
    Route::rule('store_shop/createOrder','api/store_shop.pay/createOrder');
    Route::rule('store_shop/checkOrder','api/store_shop.pay/checkOrder');
    Route::rule('store_shop/getMyOrder','api/store_shop.order/getMyOrder');
    Route::rule('store_shop/cancelMyOrder','api/store_shop.order/cancelMyOrder');
    Route::rule('store_shop/getOrderDesById','api/store_shop.order/getOrderDesById');
    Route::rule('store_shop/getLogisticsCompany','api/store_shop.order/getLogisticsCompany');
    Route::rule('store_shop/receiving','api/store_shop.pay/receiving');
    Route::rule('store_shop/payOrder','api/store_shop.pay/payOrder');


    //个人中心模块
    Route::rule('user/getAuthInfo','api/user.auth/getAuthInfo');
    Route::rule('user/getJsConfig','api/user.auth/getJsConfig');
    Route::rule('user/getAuthUserInfo','api/user.auth/getAuthUserInfo');
    Route::rule('user/getUserCenterPage','api/user.page/getUserCenterPage');
    Route::rule('user/getRrizeRecords','api/user.data/getRrizeRecords');
    Route::rule('user/getUserInfo','api/user.UserCenter/getUserInfo');
    Route::rule('user/saveUserInfo','api/user.UserCenter/saveUserInfo');
    Route::rule('user/getMemberAddressList','api/user.address/getMemberAddressList');
    Route::rule('user/deleMemberAddress','api/user.address/deleMemberAddress');
    Route::rule('user/setDefaultMemberAddress','api/user.address/setDefaultMemberAddress');
    Route::rule('user/saveMemberAddress','api/user.address/saveMemberAddress');
    Route::rule('user/queryMemberAddress','api/user.address/queryMemberAddress');
    Route::rule('user/getMarketingOrderList','api/user.order/getMarketingOrderList');
    Route::rule('user/registerOrderAddress','api/user.order/registerOrderAddress');
    Route::rule('user/getOrderDesById','api/user.order/getOrderDesById');
    Route::rule('user/getLogisticsCompany','api/user.order/getLogisticsCompany');
    Route::rule('user/receiving','api/user.order/receiving');


})->middleware(['api_allow_cross_domain','api_auth']);