<?php
/**
 * Created by PhpStorm.
 * Role: wenhan
 * Date: 2021/11/11
 * Time: 下午3:28
 */
//登录接口
Route::get('dealer/login', 'dealer/Auth/login');
Route::get('dealer/logout', 'dealer/Auth/logout');

//授权接口
Route::group('dealer', function(){
    Route::rule('index/index/getPageData','dealer/index.index/getPageData');
    Route::get('auth/getUserInfo', 'dealer/Auth/getUserInfo');
    Route::rule('auth/route','dealer/Auth/getRoute');

    Route::rule('system/resetPwd','dealer/system.user/resetPwds');

    Route::rule('upload','dealer/Upload/uploadLogo');
    Route::rule('system/getDealerInfo','dealer/system.account/getDealerInfo');
    Route::rule('system/saveDealerInfo','dealer/system.account/saveDealerInfo');
    Route::rule('system/getAuthData','dealer/system.account/getAuthData');
    Route::rule('system/checkTrademark','dealer/system.account/checkTrademark');
    Route::rule('system/checkLicense','dealer/system.account/checkLicense');
    Route::rule('system/uploadTrademark','dealer/Upload/uploadLicense');
    Route::rule('system/uploadLicense','dealer/Upload/uploadLicense');

    Route::rule('system/role/roleList','dealer/system.role/roleList');
    Route::rule('system/role/getRole','dealer/system.role/getRole');
    Route::rule('system/role/addRole','dealer/system.role/addRole');
    Route::rule('system/role/dataScope','dealer/system.role/dataScope');
    Route::rule('system/role/changeStatus','dealer/system.role/changeStatus');
    Route::rule('system/role/deleRole','dealer/system.role/deleRole');
    Route::rule('system/role/export','dealer/system.role/export');

    Route::rule('system/role/treeselect','dealer/system.menu/treeselect');
    Route::rule('system/role/roleMenuTreeselect','dealer/system.menu/roleMenuTreeselect');

    Route::rule('system/user/list','dealer/system.user/listUser');
    Route::rule('system/user/getUser','dealer/system.user/getUser');
    Route::rule('system/user/addUser','dealer/system.user/addUser');
    Route::rule('system/user/deleUser','dealer/system.user/deleUser');
    Route::rule('system/user/resetPwd','dealer/system.user/resetPwd');
    Route::rule('system/user/changeStatus','dealer/system.user/changeStatus');
    Route::rule('system/user/resetPwd','dealer/system.user/resetPwd');

    Route::rule('system/log/operationList','dealer/system.log/operationList');

    Route::rule('system/freight/getTpl','dealer/system.freight/getTpl');
    Route::rule('system/freight/saveTpl','dealer/system.freight/saveTpl');
    Route::rule('system/freight/deleTpl','dealer/system.freight/deleTpl');
    Route::rule('system/freight/queryTpl','dealer/system.freight/queryTpl');

    Route::rule('system/warehouse/warehouseList','dealer/system.warehouse/warehouseList');
    Route::rule('system/warehouse/saveWarehouse','dealer/system.warehouse/saveWarehouse');
    Route::rule('system/warehouse/deleWarehouse','dealer/system.warehouse/deleWarehouse');
    Route::rule('system/warehouse/getWarehouse','dealer/system.warehouse/getWarehouse');
    Route::rule('system/warehouse/changeWarehouseStatus','dealer/system.warehouse/changeWarehouseStatus');

    Route::rule('system/taxTpl/taxTplList','dealer/system.taxtpl/taxTplList');
    Route::rule('system/taxTpl/saveTaxTpl','dealer/system.taxtpl/saveTaxTpl');
    Route::rule('system/taxTpl/deleTaxTpl','dealer/system.taxtpl/deleTaxTpl');
    Route::rule('system/taxTpl/getTaxTpl','dealer/system.taxtpl/getTaxTpl');
    Route::rule('system/taxTpl/changeTaxTplStatus','dealer/system.taxtpl/changeTaxTplStatus');

    Route::rule('system/uploadKey','dealer/Upload/uploadKey');
    Route::rule('system/uploadCert','dealer/Upload/uploadCert');
    Route::rule('system/payment/getPayInfo','dealer/system.payment/getPayInfo');
    Route::rule('system/payment/savePayInfo','dealer/system.payment/savePayInfo');

//    公众号 小程序模块
    Route::rule('access/officialAccount/getAuthConfig','dealer/access.officialaccount/getAuthConfig');
    Route::rule('access/officialAccount/saveAuthInfo','dealer/access.officialaccount/saveAuthInfo');
    Route::rule('access/officialAccount/saveAuthConfig','dealer/access.officialaccount/saveAuthConfig');
    Route::rule('access/officialAccount/getQRCodeList','dealer/access.officialaccount/getQRCodeList');
    Route::rule('access/officialAccount/queryQRCode','dealer/access.officialaccount/queryQRCode');
    Route::rule('access/officialAccount/deleQRCode','dealer/access.officialaccount/deleQRCode');
    Route::rule('access/officialAccount/changeQRcodeStatus','dealer/access.officialaccount/changeQRcodeStatus');
    Route::rule('access/officialAccount/getUserTags','dealer/access.officialaccount/getUserTags');
    Route::rule('access/officialAccount/saveQRCode','dealer/access.officialaccount/saveQRCode');
    Route::rule('access/officialAccount/getQRCodeType','dealer/access.officialaccount/getQRCodeType');
    Route::rule('access/officialAccount/saveQRCodeGroup','dealer/access.officialaccount/saveQRCodeGroup');
    Route::rule('access/officialAccount/queryQRCodeGroup','dealer/access.officialaccount/queryQRCodeGroup');
    Route::rule('access/officialAccount/deleQRCodeGroup','dealer/access.officialaccount/deleQRCodeGroup');
    //素材管理
    Route::rule('access/material/getGroupList','dealer/access.material/getGroupList');
    Route::rule('access/material/getArticleList','dealer/access.material/getArticleList');
    Route::rule('access/material/getArticleInfo','dealer/access.material/getArticleInfo');
    Route::rule('access/material/deleArticle','dealer/access.material/deleArticle');
    Route::rule('access/material/getImgMaterial','dealer/access.material/getImgMaterial');
    Route::rule('access/material/uploadImgMaterial','dealer/access.material/uploadImgMaterial');
    Route::rule('access/material/saveGroup','dealer/access.material/saveGroup');
    Route::rule('access/material/queryGroup','dealer/access.material/queryGroup');
    Route::rule('access/material/deleGroup','dealer/access.material/deleGroup');
    Route::rule('access/material/saveArticle','dealer/access.material/saveArticle');
    Route::rule('access/uploadMaterial','dealer/Upload/uploadImgMaterial');//
    //钉钉管理
    Route::rule('access/dingding/getAuthInfo','dealer/access.dingding/getAuthInfo');
    Route::rule('access/dingding/saveAuthInfo','dealer/access.dingding/saveAuthInfo');
    //有赞管理
    Route::rule('access/zan/getAuthInfo','dealer/access.zan/getAuthInfo');
    Route::rule('access/zan/saveAuthInfo','dealer/access.zan/saveAuthInfo');
    //监控设备
    Route::rule('access/monitor/getMonitorList','dealer/access.monitor/getMonitorList');
    Route::rule('access/monitor/queryMonitor','dealer/access.monitor/queryMonitor');
    Route::rule('access/monitor/saveMonitorList','dealer/access.monitor/saveMonitorList');
    Route::rule('access/monitor/deleMonitor','dealer/access.monitor/deleMonitor');
    Route::rule('access/monitor/getSetInfo','dealer/access.monitor/getSetInfo');
    Route::rule('access/monitor/saveSetInfo','dealer/access.monitor/saveSetInfo');
    //素材库分组
    Route::rule('assets/material/getImgMaterial','dealer/assets.material/getImgMaterial');
    Route::rule('assets/material/uploadImgMaterial','dealer/assets.material/uploadImgMaterial');
    Route::rule('assets/material/uploadImg','dealer/assets.material/uploadImg');
    Route::rule('assets/material/deleImg','dealer/assets.material/deleImg');
    Route::rule('assets/material/changeGroup','dealer/assets.material/changeGroup');
    Route::rule('assets/material/saveGroup','dealer/assets.material/saveGroup');
    Route::rule('assets/material/deleGroup','dealer/assets.material/deleGroup');
    Route::rule('assets/material/queryGroup','dealer/assets.material/queryGroup');
    Route::rule('assets/material/getGroupList','dealer/assets.material/getGroupList');
    //短信模块
    Route::rule('assets/sms/getLogList','dealer/assets.sms/getLogList');
    Route::rule('assets/sms/getSmsPrice','dealer/assets.sms/getSmsPrice');
    Route::rule('assets/sms/getSmsInfo','dealer/assets.sms/getSmsInfo');
    Route::rule('assets/sms/smsPay','dealer/assets.sms/smsPay');
    Route::rule('assets/sms/saveSmsWarning','dealer/assets.sms/saveSmsWarning');
    Route::rule('assets/sms/getPayLog','dealer/assets.sms/getPayLog');
    Route::rule('assets/sms/queryPayStatus','dealer/assets.sms/queryPayStatus');
    //产品库模块
    Route::rule('assets/product/getClassList','dealer/assets.product/getClassList');
    Route::rule('assets/product/importData','dealer/assets.product/importData');
    Route::rule('assets/product/saveProductClass','dealer/assets.product/saveProductClass');
    Route::rule('assets/product/queryProductInfo','dealer/assets.product/queryProductInfo');
    Route::rule('assets/product/getProductList','dealer/assets.product/getProductList');
    Route::rule('assets/product/reductionProduct','dealer/assets.product/reductionProduct');
    Route::rule('assets/product/deleProductClass','dealer/assets.product/deleProductClass');
    Route::rule('assets/product/deleProduct','dealer/assets.product/deleProduct');
    Route::rule('assets/product/queryProductClass','dealer/assets.product/queryProductClass');
    Route::rule('assets/product/importTemplate','dealer/assets.product/importTemplate');
    Route::rule('assets/product/saveProduct','dealer/assets.product/saveProduct');
    Route::rule('assets/uploadFile','dealer/Upload/uploadFile');
    //礼品模块
    Route::rule('assets/gift/getGroupList','dealer/assets.gift/getGroupList');
    Route::rule('assets/gift/queryGroup','dealer/assets.gift/queryGroup');
    Route::rule('assets/gift/deleGroup','dealer/assets.gift/deleGroup');
    Route::rule('assets/gift/saveGroup','dealer/assets.gift/saveGroup');
    Route::rule('assets/gift/getGiftList','dealer/assets.gift/getGiftList');
    Route::rule('assets/gift/queryGiftInfo','dealer/assets.gift/queryGiftInfo');
    Route::rule('assets/gift/saveGift','dealer/assets.gift/saveGift');
    Route::rule('assets/gift/deleGift','dealer/assets.gift/deleGift');
    Route::rule('assets/gift/reductionGift','dealer/assets.gift/reductionGift');
    //红包模块
    Route::rule('assets/redpack/getRedPackList','dealer/assets.redpack/getRedPackList');
    Route::rule('assets/redpack/addRedPack','dealer/assets.redpack/addRedPack');
    Route::rule('assets/redpack/queryRedPackInfo','dealer/assets.redpack/queryRedPackInfo');
    Route::rule('assets/redpack/setRedPackStatus','dealer/assets.redpack/setRedPackStatus');
    Route::rule('assets/redpack/getRedpackPoolInfo','dealer/assets.redpack/getRedpackPoolInfo');
    Route::rule('assets/redpack/getRedpackGrantList','dealer/assets.redpack/getRedpackGrantList');
    Route::rule('assets/redpack/getRedpackGrantBill','dealer/assets.redpack/getRedpackGrantBill');
    //积分模块
    Route::rule('assets/points/getPointsSetInfo','dealer/assets.points/getPointsSetInfo');
    Route::rule('assets/points/savePointsSet','dealer/assets.points/savePointsSet');
    Route::rule('assets/points/getPointsBill','dealer/assets.points/getPointsBill');
    Route::rule('assets/points/blockMember','dealer/assets.points/blockMember');
    Route::rule('assets/points/getMemberInfo','dealer/assets.points/getMemberInfo');
    //码库 二维码管理
    Route::rule('codeStore/qrcode/listCode','dealer/code.qrcode/listCode');
    Route::rule('codeStore/qrcode/getEnableCodes','dealer/code.qrcode/getEnableCodes');
    Route::rule('codeStore/qrcode/saveEnableStatus','dealer/code.qrcode/saveEnableStatus');
    Route::rule('codeStore/qrcode/addEnableLog','dealer/code.qrcode/addEnableLog');
    Route::rule('codeStore/qrcode/deleEnableLog','dealer/code.qrcode/deleEnableLog');
    Route::rule('codeStore/qrcode/getRelProduct','dealer/code.qrcode/getRelProduct');
    Route::rule('codeStore/qrcode/getProduct','dealer/code.qrcode/getProduct');
    Route::rule('codeStore/qrcode/removeProductRel','dealer/code.qrcode/removeProductRel');
    Route::rule('codeStore/qrcode/addRelLog','dealer/code.qrcode/addRelLog');
    Route::rule('codeStore/qrcode/deleRelLog','dealer/code.qrcode/deleRelLog');
    Route::rule('codeStore/qrcode/getCodeBatch','dealer/code.qrcode/getCodeBatch');
    Route::rule('codeStore/qrcode/getTraceCodeBatch','dealer/code.qrcode/getTraceCodeBatch');
    Route::rule('codeStore/qrcode/getInvalidCodeList','dealer/code.qrcode/getInvalidCodeList');
    Route::rule('codeStore/qrcode/saveInvalidCode','dealer/code.qrcode/saveInvalidCode');
    Route::rule('codeStore/qrcode/recoverInvalidCode','dealer/code.qrcode/recoverInvalidCode');
    Route::rule('codeStore/qrcode/getMarketCodeBatch','dealer/code.qrcode/getMarketCodeBatch');
    Route::rule('codeStore/qrcode/getGuideCodeBatch','dealer/code.qrcode/getGuideCodeBatch');
    //扫码黑名单
    Route::rule('codeStore/blackList/getBlackListSet','dealer/code.blacklist/getBlackListSet');
    Route::rule('codeStore/blackList/saveBlackListSet','dealer/code.blacklist/saveBlackListSet');
    Route::rule('codeStore/blackList/getBlackList','dealer/code.blacklist/getBlackList');
    Route::rule('codeStore/blackList/saveBlackList','dealer/code.blacklist/saveBlackList');
    Route::rule('codeStore/blackList/revokeBlackList','dealer/code.blacklist/revokeBlackList');
    //客户 会员管理
    Route::rule('customer/member/saveMemberTag','dealer/customer.member/saveMemberTag');
    Route::rule('customer/member/getMemberTagList','dealer/customer.member/getMemberTagList');
    Route::rule('customer/member/deleteTag','dealer/customer.member/deleteTag');
    Route::rule('customer/member/queryTagInfo','dealer/customer.member/queryTagInfo');
    Route::rule('customer/member/getMemberList','dealer/customer.member/getMemberList');
    Route::rule('customer/member/batchTagging','dealer/customer.member/batchTagging');
    Route::rule('customer/member/batchUnTagging','dealer/customer.member/batchUnTagging');
    Route::rule('customer/member/addPoints','dealer/customer.member/addPoints');
    Route::rule('customer/member/getAssetsList','dealer/customer.member/getAssetsList');
    Route::rule('customer/member/getFieldList','dealer/customer.member/getFieldList');
    Route::rule('customer/member/saveFiled','dealer/customer.member/saveFiled');
    Route::rule('customer/member/deleField','dealer/customer.member/deleField');
    Route::rule('customer/member/queryFieldInfo','dealer/customer.member/queryFieldInfo');
    Route::rule('customer/member/changeFieldStatus','dealer/customer.member/changeFieldStatus');
    //客户 经销商管理
    Route::rule('customer/distributor/getDistributorLevelList','dealer/customer.distributor/getDistributorLevelList');
    Route::rule('customer/distributor/importData','dealer/customer.distributor/importData');
    Route::rule('customer/distributor/importDistributorTemplate','dealer/customer.distributor/importDistributorTemplate');
    Route::rule('customer/distributor/saveDistributorLevel','dealer/customer.distributor/saveDistributorLevel');
    Route::rule('customer/distributor/deleDistributorLevel','dealer/customer.distributor/deleDistributorLevel');
    Route::rule('customer/distributor/queryDistributorLevelInfo','dealer/customer.distributor/queryDistributorLevelInfo');
    Route::rule('customer/distributor/queryRegisterConfig','dealer/customer.distributor/queryRegisterConfig');
    Route::rule('customer/distributor/saveRegisterConfig','dealer/customer.distributor/saveRegisterConfig');
    Route::rule('customer/distributor/getDistributorList','dealer/customer.distributor/getDistributorList');
    Route::rule('customer/distributor/getRechargeDistributorList','dealer/customer.distributor/getRechargeDistributorList');
    Route::rule('customer/distributor/getAllSuperiorDistributorList','dealer/customer.distributor/getAllSuperiorDistributorList');
    Route::rule('customer/distributor/saveDistributor','dealer/customer.distributor/saveDistributor');
    Route::rule('customer/distributor/deleDistributor','dealer/customer.distributor/deleDistributor');
    Route::rule('customer/distributor/cutDistributor','dealer/customer.distributor/cutDistributor');
    Route::rule('customer/distributor/getDistributorInfo','dealer/customer.distributor/getDistributorInfo');
    Route::rule('customer/distributor/getSuperiorDistributorList','dealer/customer.distributor/getSuperiorDistributorList');
    Route::rule('customer/distributor/getAvailableDistributor','dealer/customer.distributor/getAvailableDistributor');
    Route::rule('customer/distributor/getDistributorById','dealer/customer.distributor/getDistributorById');
    Route::rule('customer/distributor/changeDistributorBalance','dealer/customer.distributor/changeDistributorBalance');
    Route::rule('customer/distributor/getDistributorBillLog','dealer/customer.distributor/getDistributorBillLog');
    //客户 门店管理
    Route::rule('customer/store/getStoreTypeList','dealer/customer.store/getStoreTypeList');
    Route::rule('customer/store/saveStoreType','dealer/customer.store/saveStoreType');
    Route::rule('customer/store/queryStoreTypeInfo','dealer/customer.store/queryStoreTypeInfo');
    Route::rule('customer/store/deleStoreType','dealer/customer.store/deleStoreType');
    Route::rule('customer/store/getStoreList','dealer/customer.store/getStoreList');
    Route::rule('customer/store/saveStore','dealer/customer.store/saveStore');
    Route::rule('customer/store/getStoreInfo','dealer/customer.store/getStoreInfo');
    Route::rule('customer/store/changeStoreStatus','dealer/customer.store/changeStoreStatus');
    Route::rule('customer/store/deleStore','dealer/customer.store/deleStore');
    Route::rule('customer/store/getStoreClerkList','dealer/customer.store/getStoreClerkList');
    Route::rule('customer/store/getStoreFinanceBill','dealer/customer.store/getStoreFinanceBill');
    Route::rule('customer/store/getStoreCashBill','dealer/customer.store/getStoreCashBill');
    Route::rule('customer/store/getPointsLog','dealer/customer.store/getPointsLog');
    Route::rule('customer/store/cashStore','dealer/customer.store/cashStore');
    Route::rule('customer/store/refuseCashReply','dealer/customer.store/refuseCashReply');
    Route::rule('customer/store/deleCashReply','dealer/customer.store/deleCashReply');
    Route::rule('customer/store/getStoreCashSet','dealer/customer.store/getStoreCashSet');
    Route::rule('customer/store/saveStoreCashSet','dealer/customer.store/saveStoreCashSet');
    Route::rule('customer/store/saveStorePoints','dealer/customer.store/saveStorePoints');
    Route::rule('customer/store/getAvailableStore','dealer/customer.store/getAvailableStore');
    Route::rule('customer/store/getStoreById','dealer/customer.store/getStoreById');
    //客户 业务员管理
    Route::rule('customer/salesman/getSalesmanTypeList','dealer/customer.salesman/getSalesmanTypeList');
    Route::rule('customer/salesman/saveSalesmanType','dealer/customer.salesman/saveSalesmanType');
    Route::rule('customer/salesman/querySalesmanTypeInfo','dealer/customer.salesman/querySalesmanTypeInfo');
    Route::rule('customer/salesman/deleSalesmanType','dealer/customer.salesman/deleSalesmanType');
    Route::rule('customer/salesman/saveSalesman','dealer/customer.salesman/saveSalesman');
    Route::rule('customer/salesman/getSalesmanList','dealer/customer.salesman/getSalesmanList');
    Route::rule('customer/salesman/deleSalesman','dealer/customer.salesman/deleSalesman');
    Route::rule('customer/salesman/cutSalesman','dealer/customer.salesman/cutSalesman');
    Route::rule('customer/salesman/getSalesmanInfo','dealer/customer.salesman/getSalesmanInfo');
    //客户 基础管理
    Route::rule('customer/basics/getCustomerAreaList','dealer/customer.basics/getCustomerAreaList');
    Route::rule('customer/basics/saveCustomerArea','dealer/customer.basics/saveCustomerArea');
    Route::rule('customer/basics/deleCustomerArea','dealer/customer.basics/deleCustomerArea');
    Route::rule('customer/basics/queryCustomerArea','dealer/customer.basics/queryCustomerArea');
    Route::rule('customer/basics/queryBasicSetInfo','dealer/customer.basics/queryBasicSetInfo');
    Route::rule('customer/basics/saveBasicSetInfo','dealer/customer.basics/saveBasicSetInfo');
    Route::rule('customer/basics/queryUserSetInfo','dealer/customer.basics/queryUserSetInfo');
    Route::rule('customer/basics/saveUserSetInfo','dealer/customer.basics/saveUserSetInfo');
    //客户 公告管理
    Route::rule('customer/notice/getNoticeList','dealer/customer.notice/getNoticeList');
    Route::rule('customer/notice/saveNotice','dealer/customer.notice/saveNotice');
    Route::rule('customer/notice/deleNotice','dealer/customer.notice/deleNotice');
    Route::rule('customer/notice/queryNoticeInfo','dealer/customer.notice/queryNoticeInfo');

    //应用模块 溯源
    Route::rule('app/trace/getPageData','dealer/app.trace.index/getPageData');
    Route::rule('app/trace/getTplList','dealer/app.trace.tpl/getTplList');
    Route::rule('app/trace/deleTpl','dealer/app.trace.tpl/deleTpl');
    Route::rule('app/trace/getTplInfo','dealer/app.trace.tpl/getTplInfo');
    Route::rule('app/trace/saveTraceTpl','dealer/app.trace.tpl/saveTraceTpl');
    Route::rule('app/trace/saveProductBatch','dealer/app.trace.productbatch/saveProductBatch');
    Route::rule('app/trace/getProductBatchList','dealer/app.trace.productbatch/getProductBatchList');
    Route::rule('app/trace/deleProductBatch','dealer/app.trace.productbatch/deleProductBatch');
    Route::rule('app/trace/getBatchInfo','dealer/app.trace.productbatch/getBatchInfo');
    Route::rule('app/trace/saveCodebBatch','dealer/app.trace.codebatch/saveCodebBatch');
    Route::rule('app/trace/getCodeBatchList','dealer/app.trace.codebatch/getCodeBatchList');
    Route::rule('app/trace/deleCodeBatch','dealer/app.trace.codebatch/deleCodeBatch');
    Route::rule('app/trace/queryTraceInfo','dealer/app.trace.traceinfo/queryTraceInfo');
    Route::rule('app/trace/queryTraceInfo','dealer/app.trace.traceinfo/queryTraceInfo');
    Route::rule('app/trace/getTraceQueryDetail','dealer/app.trace.traceinfo/getTraceQueryDetail');
    //应用模块 微商城
    Route::rule('app/mall/getMallDashboard','dealer/app.mall.index/getMallDashboard');
    Route::rule('app/mall/saveMallTpl','dealer/app.mall.tpl/saveMallTpl');
    Route::rule('app/mall/getTplInfo','dealer/app.mall.tpl/getTplInfo');
    Route::rule('app/mall/saveProductClass','dealer/app.mall.product/saveProductClass');
    Route::rule('app/mall/getClassList','dealer/app.mall.product/getClassList');
    Route::rule('app/mall/getClassLists','dealer/app.mall.product/getClassLists');
    Route::rule('app/mall/queryProductClass','dealer/app.mall.product/queryProductClass');
    Route::rule('app/mall/deleProductClass','dealer/app.mall.product/deleProductClass');
    Route::rule('app/mall/getGoodsList','dealer/app.mall.product/getGoodsList');
    Route::rule('app/mall/queryGoodsInfo','dealer/app.mall.product/queryGoodsInfo');
    Route::rule('app/mall/saveGoods','dealer/app.mall.product/saveGoods');
    Route::rule('app/mall/cutGoods','dealer/app.mall.product/cutGoods');
    Route::rule('app/mall/upGoods','dealer/app.mall.product/upGoods');
    Route::rule('app/mall/getGoodsJudge','dealer/app.mall.judge/getGoodsJudge');
    Route::rule('app/mall/deleJudge','dealer/app.mall.judge/deleJudge');
    Route::rule('app/mall/saveJudge','dealer/app.mall.judge/saveJudge');
    //微分销
    Route::rule('app/mall/saveDistributionSet','dealer/app.mall.distribution/saveDistributionSet');
    Route::rule('app/mall/getDistributionInfo','dealer/app.mall.distribution/getDistributionInfo');
    Route::rule('app/mall/saveDistributionUser','dealer/app.mall.distribution/saveDistributionUser');
    Route::rule('app/mall/getDistributionUser','dealer/app.mall.distribution/getDistributionUser');
    Route::rule('app/mall/getFenxiaoyuanList','dealer/app.mall.distribution/getFenxiaoyuanList');
    Route::rule('app/mall/getFenxiaoyuanChild','dealer/app.mall.distribution/getFenxiaoyuanChild');
    Route::rule('app/mall/getFenxiaoOrderList','dealer/app.mall.distribution/getFenxiaoOrderList');
    Route::rule('app/mall/getFenxiaoData','dealer/app.mall.distribution/getFenxiaoData');
    Route::rule('app/mall/getFenxiaoCashOrder','dealer/app.mall.distribution/getFenxiaoCashOrder');
    Route::rule('app/mall/passCashOrder','dealer/app.mall.distribution/passCashOrder');
    Route::rule('app/mall/refuseCashOrder','dealer/app.mall.distribution/refuseCashOrder');
    //积分商城
    Route::rule('app/points/getPointsDashboard','dealer/app.points.index/getPointsDashboard');
    Route::rule('app/points/savePointsTpl','dealer/app.points.tpl/savePointsTpl');
    Route::rule('app/points/getTplInfo','dealer/app.points.tpl/getTplInfo');
    Route::rule('app/points/getPointsRule','dealer/app.points.rule/getPointsRule');
    Route::rule('app/points/savePointsRule','dealer/app.points.rule/savePointsRule');
    Route::rule('app/points/getClassList','dealer/app.points.giftclass/getClassList');
    Route::rule('app/points/getClassLists','dealer/app.points.giftclass/getClassLists');
    Route::rule('app/points/savePointsClass','dealer/app.points.giftclass/savePointsClass');
    Route::rule('app/points/delePointsClass','dealer/app.points.giftclass/delePointsClass');
    Route::rule('app/points/queryPointsClass','dealer/app.points.giftclass/queryPointsClass');
    Route::rule('app/points/savePointsGift','dealer/app.points.gifts/savePointsGift');
    Route::rule('app/points/getPointsGiftList','dealer/app.points.gifts/getPointsGiftList');
    Route::rule('app/points/cutPointsGift','dealer/app.points.gifts/cutPointsGift');
    Route::rule('app/points/queryGiftInfo','dealer/app.points.gifts/queryGiftInfo');
    Route::rule('app/points/queryPointsMallData','dealer/app.points.gifts/queryPointsMallData');
    //智能物流
    Route::rule('app/logistics/getWarehouseList','dealer/app.logistics.warehouse/getWarehouseList');
    Route::rule('app/logistics/saveWarehouse','dealer/app.logistics.warehouse/saveWarehouse');
    Route::rule('app/logistics/deleWarehouse','dealer/app.logistics.warehouse/deleWarehouse');
    Route::rule('app/logistics/getWarehouseInfo','dealer/app.logistics.warehouse/getWarehouseInfo');
    Route::rule('app/logistics/createRkCode','dealer/app.logistics.RKManage/createRkCode');
    Route::rule('app/logistics/saveRkOrder','dealer/app.logistics.RKManage/saveRkOrder');
    Route::rule('app/logistics/getCodeList','dealer/app.logistics.RKManage/getCodeList');
    Route::rule('app/logistics/getRkOrderList','dealer/app.logistics.RKManage/getRkOrderList');
    Route::rule('app/logistics/deleRkOrder','dealer/app.logistics.RKManage/deleRkOrder');
    Route::rule('app/logistics/quickDeliver','dealer/app.logistics.RKManage/quickDeliver');
    Route::rule('app/logistics/getRkOrderInfo','dealer/app.logistics.RKManage/getRkOrderInfo');
    Route::rule('app/logistics/createCkCode','dealer/app.logistics.CKManage/createCkCode');
    Route::rule('app/logistics/saveCkOrder','dealer/app.logistics.CKManage/saveCkOrder');
    Route::rule('app/logistics/getCkOrderList','dealer/app.logistics.CKManage/getCkOrderList');
    Route::rule('app/logistics/getCkOrderInfo','dealer/app.logistics.CKManage/getCkOrderInfo');
    Route::rule('app/logistics/saveScanRkOrder','dealer/app.logistics.CKManage/saveScanRkOrder');
    Route::rule('app/logistics/getCkCodeList','dealer/app.logistics.CKManage/getCkCodeList');
    Route::rule('app/logistics/deleCkOrder','dealer/app.logistics.CKManage/deleCkOrder');
    Route::rule('app/logistics/finishCkOrder','dealer/app.logistics.CKManage/finishCkOrder');
    Route::rule('app/logistics/getThOrderList','dealer/app.logistics.THManage/getThOrderList');
    Route::rule('app/logistics/getThOrderInfo','dealer/app.logistics.THManage/getThOrderInfo');
    Route::rule('app/logistics/saveExpressOrder','dealer/app.logistics.THManage/saveExpressOrder');
    Route::rule('app/logistics/checkThOrder','dealer/app.logistics.THManage/checkThOrder');
    Route::rule('app/logistics/deleThOrder','dealer/app.logistics.THManage/deleThOrder');
    Route::rule('app/logistics/getThCodeList','dealer/app.logistics.THManage/getThCodeList');
    Route::rule('app/logistics/getChOrderList','dealer/app.logistics.Statistics/getChOrderList');
    Route::rule('app/logistics/getChOrderBill','dealer/app.logistics.Statistics/getChOrderBill');
    Route::rule('app/logistics/getBillDes','dealer/app.logistics.Statistics/getBillDes');

    Route::rule('app/logistics/createDcCode','dealer/app.logistics.DCManage/createDcCode');
    Route::rule('app/logistics/saveDcOrder','dealer/app.logistics.DCManage/saveDcOrder');
    Route::rule('app/logistics/getDcOrderList','dealer/app.logistics.DCManage/getDcOrderList');
    Route::rule('app/logistics/getDcOrderInfo','dealer/app.logistics.DCManage/getDcOrderInfo');
    Route::rule('app/logistics/deleDcOrder','dealer/app.logistics.DCManage/deleDcOrder');
    Route::rule('app/logistics/getLogCodeBatch','dealer/app.logistics.Trace/getLogCodeBatch');
    Route::rule('app/logistics/queryCodeLink','dealer/app.logistics.Trace/queryCodeLink');

    Route::rule('app/logistics/getBasicSetInfo','dealer/app.logistics.BasicSet/getBasicSetInfo');
    Route::rule('app/logistics/saveBasicSetInfo','dealer/app.logistics.BasicSet/saveBasicSetInfo');
    Route::rule('app/logistics/getTplInfo','dealer/app.logistics.Template/getTplInfo');
    Route::rule('app/logistics/saveTraceTpl','dealer/app.logistics.Template/saveTraceTpl');
    Route::rule('app/logistics/getPageData','dealer/app.logistics.Board/getPageData');
    //二维码营销
    Route::rule('app/qrcode/saveScanTpl','dealer/app.qrcode.ScanTpl/saveScanTpl');
    Route::rule('app/qrcode/getTplList','dealer/app.qrcode.ScanTpl/getTplList');
    Route::rule('app/qrcode/getTplInfo','dealer/app.qrcode.ScanTpl/getTplInfo');
    Route::rule('app/qrcode/saveActivity','dealer/app.qrcode.Activity/saveActivity');
    Route::rule('app/qrcode/getActivityList','dealer/app.qrcode.Activity/getActivityList');
    Route::rule('app/qrcode/setActivityStatus','dealer/app.qrcode.Activity/setActivityStatus');
    Route::rule('app/qrcode/deleActivity','dealer/app.qrcode.Activity/deleActivity');
    Route::rule('app/qrcode/getActivityInfo','dealer/app.qrcode.Activity/getActivityInfo');
    Route::rule('app/qrcode/getScanBill','dealer/app.qrcode.ScanBill/getScanBill');
    Route::rule('app/qrcode/getPrizeLog','dealer/app.qrcode.ScanBill/getPrizeLog');
    Route::rule('app/qrcode/getScanNum','dealer/app.qrcode.Statistics/getScanNum');
    Route::rule('app/qrcode/getScanArea','dealer/app.qrcode.Statistics/getScanArea');
    Route::rule('app/qrcode/getScanUser','dealer/app.qrcode.Statistics/getScanUser');
    Route::rule('app/qrcode/getPageData','dealer/app.qrcode.Statistics/getPageData');
    Route::rule('app/qrcode/getRegisterList','dealer/app.qrcode.Register/getRegisterList');
    Route::rule('app/qrcode/deleRegisterInfo','dealer/app.qrcode.Register/deleRegisterInfo');
    Route::rule('app/qrcode/changeRegisterStatus','dealer/app.qrcode.Register/changeRegisterStatus');
    Route::rule('app/qrcode/importRegister','dealer/app.qrcode.Register/importRegister');
    Route::rule('app/qrcode/exportAward','dealer/app.qrcode.ScanBill/exportAward');
    Route::rule('app/qrcode/exportBill','dealer/app.qrcode.ScanBill/exportBill');

    //订单管理
    Route::rule('order/orderManage/getPointsOrderList','dealer/order.OrderManage/getPointsOrderList');
    Route::rule('order/orderManage/markShipment','dealer/order.OrderManage/markShipment');
    Route::rule('order/orderManage/getMallOrderList','dealer/order.OrderManage/getMallOrderList');
    Route::rule('order/orderManage/markMallShipment','dealer/order.OrderManage/markMallShipment');
    Route::rule('order/orderManage/getAddressInfo','dealer/order.Address/getAddressInfo');
    Route::rule('order/orderManage/getMarketingOrderList','dealer/order.OrderManage/getMarketingOrderList');
    Route::rule('order/orderManage/markQrcodeShipment','dealer/order.OrderManage/markQrcodeShipment');

    //导购模块
    Route::rule('app/guide/saveGuide','dealer/app.guide.Index/saveGuide');
    Route::rule('app/guide/delGuide','dealer/app.guide.Index/delGuide');
    Route::rule('app/guide/checkGuide','dealer/app.guide.Index/checkGuide');
    Route::rule('app/guide/getGuideInfo','dealer/app.guide.Index/getGuideInfo');
    Route::rule('app/guide/getGuideList','dealer/app.guide.Index/getGuideList');
    Route::rule('app/guide/getGuideGroupList','dealer/app.guide.GroupManage/getGuideGroupList');
    Route::rule('app/guide/saveGuideGroup','dealer/app.guide.GroupManage/saveGuideGroup');
    Route::rule('app/guide/deleGuideGroup','dealer/app.guide.GroupManage/deleGuideGroup');
    Route::rule('app/guide/getGuideGroupInfo','dealer/app.guide.GroupManage/getGuideGroupInfo');
    Route::rule('app/guide/queryUserSetInfo','dealer/app.guide.User/queryUserSetInfo');
    Route::rule('app/guide/saveUserSetInfo','dealer/app.guide.User/saveUserSetInfo');
    Route::rule('app/guide/getTplList','dealer/app.guide.ScanTpl/getTplList');
    Route::rule('app/guide/getTplInfo','dealer/app.guide.ScanTpl/getTplInfo');
    Route::rule('app/guide/saveScanTpl','dealer/app.guide.ScanTpl/saveScanTpl');
    Route::rule('app/guide/getActivityList','dealer/app.guide.Activity/getActivityList');
    Route::rule('app/guide/setActivityStatus','dealer/app.guide.Activity/setActivityStatus');
    Route::rule('app/guide/deleActivity','dealer/app.guide.Activity/deleActivity');
    Route::rule('app/guide/getActivityInfo','dealer/app.guide.Activity/getActivityInfo');
    Route::rule('app/guide/saveActivity','dealer/app.guide.Activity/saveActivity');
    Route::rule('app/guide/getScanBill','dealer/app.guide.ScanBill/getScanBill');
    Route::rule('app/guide/getPrizeLog','dealer/app.guide.ScanBill/getPrizeLog');
    Route::rule('app/guide/getScanNum','dealer/app.guide.Statistics/getScanNum');
    Route::rule('app/guide/getScanArea','dealer/app.guide.Statistics/getScanArea');
    Route::rule('app/guide/getScanRank','dealer/app.guide.Statistics/getScanRank');
    Route::rule('app/guide/getGiftsNum','dealer/app.guide.Statistics/getGiftsNum');
    Route::rule('app/guide/getPageData','dealer/app.guide.Statistics/getGiftsNum');

    //智慧门店
    Route::rule('app/store/getStoreList','dealer/app.store.Index/getStoreList');
    Route::rule('app/store/saveStoreAuth','dealer/app.store.Index/saveStoreAuth');
    Route::rule('app/store/getStoreInfo','dealer/app.store.Index/getStoreInfo');
    Route::rule('app/store/getStoreGoodsClass','dealer/app.store.Goods/getStoreGoodsClass');
    Route::rule('app/store/saveStoreGoodsClass','dealer/app.store.Goods/saveStoreGoodsClass');
    Route::rule('app/store/deleStoreGoodsClass','dealer/app.store.Goods/deleStoreGoodsClass');
    Route::rule('app/store/queryStoreGoodsClass','dealer/app.store.Goods/queryStoreGoodsClass');
    Route::rule('app/store/saveSelfGoods','dealer/app.store.Goods/saveSelfGoods');
    Route::rule('app/store/getSelfGoodsList','dealer/app.store.Goods/getSelfGoodsList');
    Route::rule('app/store/deleSelfGoods','dealer/app.store.Goods/deleSelfGoods');
    Route::rule('app/store/querySelfGoodsInfo','dealer/app.store.Goods/querySelfGoodsInfo');
    Route::rule('app/store/getStoreOrderList','dealer/app.store.Order/getStoreOrderList');
    Route::rule('app/store/markStoreShipment','dealer/app.store.Order/markStoreShipment');
    Route::rule('app/store/getOrderAnalysisData','dealer/app.store.Data/getOrderAnalysisData');
    Route::rule('app/store/getOrderStatisticsData','dealer/app.store.Data/getOrderStatisticsData');
    Route::rule('app/store/getProductAnalysisData','dealer/app.store.Data/getProductAnalysisData');
    Route::rule('app/store/getProductPanelAnalysisData','dealer/app.store.Data/getProductPanelAnalysisData');
    Route::rule('app/store/getSurveyData','dealer/app.store.Data/getSurveyData');
})->middleware(['dealer_auth']);